controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    gripper_controller:
      type: forward_command_controller/ForwardCommandController

gripper_controller:
  ros__parameters:
    joints:
      - gripper_left_finger_joint
      - gripper_right_finger_joint
    interface_name: position
